# Generated by Django 5.0.6 on 2024-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0004_resume_analysis_results_resume_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
