# Generated by Django 5.0.6 on 2024-07-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0005_resume_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_description',
        ),
    ]
