# Generated by Django 5.0.6 on 2024-07-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0008_alter_resume_analysis_results_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
